# Generated by Django 2.2.3 on 2019-07-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('HIGHSCHOOL', 'HIGHSCHOOL'), ('UNIVERSITY', 'UNIVERSITY'), ('GRADUATED', 'GRADUATED')], default='GRADUATED', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
