# Generated by Django 2.2.3 on 2019-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
