# Generated by Django 2.2.3 on 2019-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
